# Generated by Django 5.1.6 on 2025-02-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='events/')),
                ('description', models.TextField()),
            ],
        ),
    ]
