# Generated by Django 5.1.6 on 2025-03-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozilla', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sections', models.JSONField()),
                ('duration', models.CharField(max_length=50)),
                ('eligibility', models.CharField(max_length=255)),
                ('syllabus', models.FileField(upload_to='syllabus/')),
                ('availability_status', models.CharField(default='Course will be available soon.', max_length=255)),
            ],
        ),
    ]
