# Generated by Django 5.1.6 on 2025-03-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozilla', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Curriculum Inclusion', max_length=255)),
                ('items', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Deliverables', max_length=255)),
                ('items', models.JSONField()),
            ],
        ),
    ]
