# Generated by Django 5.1.6 on 2025-03-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozilla', '0004_curriculuminclusion_deliverable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
