# Generated by Django 5.1.6 on 2025-03-10 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mozilla', '0009_alter_registration_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='email',
            new_name='username',
        ),
    ]
